server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/PersonalCenter?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  server:
    endpoint: http://192.168.1.8:9000
    accessKey: minioadmin
    secretKey: minioadmin
